#!/bin/bash
set -euo pipefail

# Set any environment variables here
# These are inherited by all processes, *except* RStudio

# Tell gh-scoped-creds which GitHub app to use for push access
# See https://github.com/jupyterhub/gh-scoped-creds#github-app-configuration
export GH_SCOPED_CREDS_CLIENT_ID="Iv1.bd27058fd393e285"
export GH_SCOPED_CREDS_APP_URL="https://github.com/apps/cryocloud-github-access"

# Enable jupyter-myst-build-proxy post-build step which adds a nice Rebuild button
export JUPYTER_MYST_BUILD_PROXY_POSTBUILD="true"

exec "$@"
